package modules

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/huh"
	"github.com/sresarehumantoo/dotfiles/src/core"
	"golang.org/x/term"
)

type pluginOption struct {
	Name     string
	Desc     string
	Category string
}

var extendedPluginOptions = []pluginOption{
	// Container & Orchestration
	{"kubectl", "Kubernetes CLI completions & aliases", "Container & Orchestration"},
	{"helm", "Helm completions", "Container & Orchestration"},
	{"docker-compose", "Docker Compose completions & aliases", "Container & Orchestration"},

	// Cloud
	{"aws", "AWS CLI completions", "Cloud"},
	{"gcloud", "Google Cloud SDK completions", "Cloud"},
	{"azure", "Azure CLI completions", "Cloud"},

	// Languages & Tools
	{"npm", "npm completions & aliases", "Languages & Tools"},
	{"yarn", "Yarn completions & aliases", "Languages & Tools"},
	{"pip", "pip completions", "Languages & Tools"},
	{"rust", "Rust/Cargo completions", "Languages & Tools"},
	{"python", "Python aliases & helpers", "Languages & Tools"},
	{"ruby", "Ruby aliases & helpers", "Languages & Tools"},
	{"dotnet", ".NET CLI completions", "Languages & Tools"},

	// DevOps
	{"ansible", "Ansible completions & aliases", "DevOps"},
	{"vagrant", "Vagrant completions & aliases", "DevOps"},

	// Utilities
	{"sudo", "Double-ESC to prefix sudo", "Utilities"},
	{"rsync", "Rsync aliases", "Utilities"},
	{"systemd", "Systemd aliases", "Utilities"},
	{"encode64", "Base64 encode/decode helpers", "Utilities"},
	{"jsontools", "JSON formatting helpers", "Utilities"},
	{"urltools", "URL encode/decode helpers", "Utilities"},
	{"command-not-found", "Suggest packages for unknown commands", "Utilities"},
}

// RunExtendedPluginMenu shows an interactive multi-select for extended OMZ plugins.
// Returns the selected plugin names.
func RunExtendedPluginMenu() ([]string, error) {
	if !term.IsTerminal(int(os.Stdin.Fd())) {
		core.Warn("stdin is not a terminal — skipping extended plugin menu")
		return core.Cfg.ExtendedPlugins, nil
	}

	// Build options grouped by category
	var options []huh.Option[string]
	lastCat := ""
	for _, p := range extendedPluginOptions {
		if p.Category != lastCat {
			lastCat = p.Category
		}
		label := fmt.Sprintf("%s — %s", p.Name, p.Desc)
		options = append(options, huh.NewOption(label, p.Name))
	}

	// Pre-select from saved config
	previous := make(map[string]bool, len(core.Cfg.ExtendedPlugins))
	for _, p := range core.Cfg.ExtendedPlugins {
		previous[p] = true
	}

	selected := make([]string, len(core.Cfg.ExtendedPlugins))
	copy(selected, core.Cfg.ExtendedPlugins)

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewMultiSelect[string]().
				Title("Extended OMZ Plugins").
				Description("Space to toggle, Enter to confirm, Esc to cancel").
				Options(options...).
				Value(&selected),
		),
	)

	if err := form.Run(); err != nil {
		if errors.Is(err, huh.ErrUserAborted) {
			core.Info("extended plugin selection cancelled — keeping existing config")
			return core.Cfg.ExtendedPlugins, nil
		}
		return nil, fmt.Errorf("plugin menu: %w", err)
	}

	// Show feedback about what changed
	newSet := make(map[string]bool, len(selected))
	for _, p := range selected {
		newSet[p] = true
	}

	var added, removed []string
	for _, p := range selected {
		if !previous[p] {
			added = append(added, p)
		}
	}
	for p := range previous {
		if !newSet[p] {
			removed = append(removed, p)
		}
	}

	if len(added) == 0 && len(removed) == 0 {
		if len(selected) > 0 {
			core.Info("extended plugins unchanged (%d selected)", len(selected))
		} else {
			core.Info("no extended plugins selected")
		}
	} else {
		if len(added) > 0 {
			core.Ok("added: %s", strings.Join(added, ", "))
		}
		if len(removed) > 0 {
			core.Info("removed: %s", strings.Join(removed, ", "))
		}
		core.Info("total extended plugins: %d", len(selected))
	}

	return selected, nil
}

// WriteExtendedPluginsFile writes the generated plugins.zsh sourced by zshrc.
func WriteExtendedPluginsFile(plugins []string) error {
	dir := filepath.Join(core.XDGConfigHome(), "dfinstall")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create dfinstall config dir: %w", err)
	}

	path := filepath.Join(dir, "plugins.zsh")

	var sb strings.Builder
	sb.WriteString("# Generated by dfinstall — do not edit manually.\n")
	sb.WriteString("# Re-run: dfinstall install omz --extended\n\n")

	if len(plugins) > 0 {
		sb.WriteString("DFINSTALL_EXTENDED_PLUGINS=(\n")
		for _, p := range plugins {
			sb.WriteString("  " + p + "\n")
		}
		sb.WriteString(")\n")
	} else {
		sb.WriteString("DFINSTALL_EXTENDED_PLUGINS=()\n")
	}

	if err := os.WriteFile(path, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("write plugins.zsh: %w", err)
	}

	core.Ok("wrote %s", path)
	return nil
}

// ExtendedPluginsFilePath returns the path to the generated plugins.zsh file.
func ExtendedPluginsFilePath() string {
	return filepath.Join(core.XDGConfigHome(), "dfinstall", "plugins.zsh")
}
