package modules

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/sresarehumantoo/dotfiles/src/core"
)

// Windows interop without relying on $PATH.
//
// wsl.conf sets `appendWindowsPath=false` (see the long comment there), so the
// Windows PATH is no longer merged into $PATH and a bare `cmd.exe` does not
// resolve. Everything here therefore addresses Windows binaries by absolute
// path, discovered through `wslpath`, which is a native Linux ELF shipped
// inside the distro, so it needs no interop of its own and works even when
// nothing Windows-ish is on PATH. That breaks the chicken-and-egg where the
// module that turns the PATH off needed the PATH to run.

// winSearchDirs are the Windows directories searched for shim targets, in
// order; first hit wins. Written in Windows form and translated by wslpath so
// a non-C: system drive or a non-default automount root still resolves.
var winSearchDirs = []string{
	`C:\Windows\System32`,
	`C:\Windows`,
	`C:\Windows\System32\WindowsPowerShell\v1.0`,
	`C:\Program Files\PowerShell\7`,
}

// winShimNames are the Windows executables shimmed into ~/.local/bin so that
// dropping the Windows PATH is invisible in day-to-day use.
//
// The first five are load-bearing, not conveniences: this repo calls them by
// bare name and would break without them: cmd.exe (wsl.go's own
// resolveWinHome), powershell.exe + tasklist.exe + taskkill.exe (demorec's
// whole WSL capture and stop path, which cannot use `kill` because signals do
// not cross the interop boundary), and wsl.exe (wsl-restart). The rest are
// there so typing a familiar command still works.
var winShimNames = []string{
	"cmd.exe",
	"powershell.exe",
	"tasklist.exe",
	"taskkill.exe",
	"wsl.exe",
	"pwsh.exe",
	"clip.exe",
	"where.exe",
	"ipconfig.exe",
	"explorer.exe",
	"notepad.exe",
	"winget.exe",
}

// winPathCache memoizes wslpath translations. resolveWinHome is called from
// Install, Status *and* doctor, each of which used to spawn its own cmd.exe;
// on WSL that is a Windows process launch each time.
var (
	winPathCache   = map[string]string{}
	winPathCacheMu sync.Mutex
)

// winToLinux translates a Windows path to its WSL mount path and returns "" if
// the result does not exist. wslpath is pure string translation, so the Stat is
// what actually decides whether the path is real.
func winToLinux(winPath string) string {
	winPathCacheMu.Lock()
	if cached, ok := winPathCache[winPath]; ok {
		winPathCacheMu.Unlock()
		return cached
	}
	winPathCacheMu.Unlock()

	resolved := ""
	// context.Background: shared with Status() and doctor, neither of which has
	// a context to inherit. Bounded by ProbeTimeout inside runProbe.
	if out, err := runProbe(context.Background(), "wslpath", "-u", winPath); err == nil {
		p := strings.TrimSpace(string(out))
		if p != "" {
			if _, err := os.Stat(p); err == nil {
				resolved = p
			}
		}
	}

	winPathCacheMu.Lock()
	winPathCache[winPath] = resolved
	winPathCacheMu.Unlock()
	return resolved
}

// winBinary returns the absolute WSL path to a Windows executable, or "".
func winBinary(name string) string {
	for _, dir := range winSearchDirs {
		linuxDir := winToLinux(dir)
		if linuxDir == "" {
			continue
		}
		candidate := filepath.Join(linuxDir, name)
		if fi, err := os.Stat(candidate); err == nil && !fi.IsDir() {
			return candidate
		}
	}
	return ""
}

// hasInterop reports whether Windows processes can actually be launched.
//
// This is deliberately NOT `exec.LookPath("cmd.exe")` any more. With
// appendWindowsPath=false that lookup fails on a perfectly healthy system, and
// the old code read the failure as "interop is off" and skipped installing
// .wslconfig and the home symlink forever. Two independent things are checked:
// the binfmt_misc handler that makes an .exe runnable, and that cmd.exe is
// actually on disk where wslpath says it should be.
func hasInterop() bool {
	registered := false
	// WSL renamed the handler; newer builds register WSLInterop-late instead.
	for _, h := range []string{"WSLInterop", "WSLInterop-late"} {
		if _, err := os.Stat(filepath.Join("/proc/sys/fs/binfmt_misc", h)); err == nil {
			registered = true
			break
		}
	}
	if !registered {
		return false
	}
	return winBinary("cmd.exe") != ""
}

// shimDir is where generated shims live. Already on PATH (path.zsh prepends it)
// and on ext4, so command lookup for these never touches 9p.
func shimDir() string { return core.HomeTarget(".local", "bin") }

const shimHeader = "# Generated by dfinstall (wsl module). Do not edit."

// shimBody is a wrapper script rather than a symlink on purpose. A symlink to
// an .exe does work through binfmt_misc, but a two-line `exec` wrapper has no
// dependency on how the kernel resolves the link before matching the MZ magic,
// and it keeps the resolved absolute path visible in the file for debugging.
// The extra fork is irrelevant next to the cost of starting a Windows process.
func shimBody(target string) string {
	return fmt.Sprintf("#!/bin/sh\n%s\n# Target verified present at install time.\nexec %s \"$@\"\n",
		shimHeader, shellQuote(target))
}

// shellQuote single-quotes a path for /bin/sh. Windows paths can contain
// spaces ("Program Files") and the mount root is user-configurable, so this
// cannot be left bare.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// installWinShims writes a wrapper into ~/.local/bin for every Windows binary
// it can actually find. Returns the names written.
func installWinShims() []string {
	// Defensive: Install() already returns before reaching here under --dry-run,
	// but os.WriteFile below is not guarded the way core.LinkFile/EnsureDir are,
	// so a future caller must not be able to write real files during a dry run.
	if core.DryRun {
		core.Info("would install Windows exe shims into %s", shimDir())
		return nil
	}

	dir := shimDir()
	if err := core.CheckTarget(dir); err != nil {
		core.Warn("skipping Windows shims: %v", err)
		return nil
	}
	if err := core.EnsureDir(dir); err != nil {
		core.Warn("could not create %s: %v", dir, err)
		return nil
	}

	var written, missing []string
	for _, name := range winShimNames {
		target := winBinary(name)
		if target == "" {
			missing = append(missing, name)
			continue
		}
		dst := filepath.Join(dir, name)
		body := []byte(shimBody(target))

		// Don't rewrite an identical shim; keeps `install` idempotent and
		// leaves mtimes alone.
		if existing, err := os.ReadFile(dst); err == nil && string(existing) == string(body) {
			written = append(written, name)
			continue
		}
		// Refuse to clobber anything that isn't ours. A user may legitimately
		// have their own wrapper here.
		if existing, err := os.ReadFile(dst); err == nil && !strings.Contains(string(existing), shimHeader) {
			core.Warn("%s exists and was not written by dfinstall, leaving it alone", dst)
			continue
		}
		if err := os.WriteFile(dst, body, 0o755); err != nil {
			core.Warn("could not write shim %s: %v", dst, err)
			continue
		}
		written = append(written, name)
	}

	if len(written) > 0 {
		core.Ok("Windows shims installed (%d): %s", len(written), strings.Join(written, " "))
	}
	// Only worth mentioning the load-bearing ones; pwsh/winget are commonly absent.
	var importantMissing []string
	for _, n := range missing {
		switch n {
		case "cmd.exe", "powershell.exe", "tasklist.exe", "taskkill.exe", "wsl.exe":
			importantMissing = append(importantMissing, n)
		}
	}
	if len(importantMissing) > 0 {
		core.Warn("could not locate: %s (demorec/wsl-restart may not work)",
			strings.Join(importantMissing, " "))
	}
	return written
}

// removeWinShims deletes only the wrappers dfinstall itself wrote.
func removeWinShims() int {
	if core.DryRun {
		return 0
	}
	dir := shimDir()
	if core.CheckTarget(dir) != nil {
		return 0
	}
	var removed int
	for _, name := range winShimNames {
		p := filepath.Join(dir, name)
		data, err := os.ReadFile(p)
		if err != nil || !strings.Contains(string(data), shimHeader) {
			continue
		}
		if err := os.Remove(p); err == nil {
			removed++
		}
	}
	return removed
}

// countWinShims reports how many shims are currently in place, for Status.
func countWinShims() (present, expected int) {
	dir := shimDir()
	if core.CheckTarget(dir) != nil {
		return 0, 0
	}
	for _, name := range winShimNames {
		if winBinary(name) == "" {
			continue // not available on this host; not expected
		}
		expected++
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err == nil && strings.Contains(string(data), shimHeader) {
			present++
		}
	}
	return present, expected
}

// ── Host sizing for .wslconfig ────────────────────────────────────────────

// hostSpecs are the Windows host's real resources, as opposed to whatever the
// VM currently has. Reading nproc/meminfo inside WSL is circular: those already
// reflect the .wslconfig this code is about to write.
type hostSpecs struct {
	logicalCPUs int
	memBytes    uint64
}

// detectHostSpecs asks Windows. Either field may be zero if that probe failed;
// callers must treat zero as "omit the key", never as "use a default".
func detectHostSpecs(ctx context.Context) hostSpecs {
	var s hostSpecs

	// NUMBER_OF_PROCESSORS is a plain environment variable, so cmd.exe answers
	// it without spinning up anything, far cheaper than the PowerShell probe.
	if cmdExe := winBinary("cmd.exe"); cmdExe != "" {
		if out, err := runProbe(ctx, cmdExe, "/C", "echo %NUMBER_OF_PROCESSORS%"); err == nil {
			txt := strings.TrimSpace(strings.ReplaceAll(string(out), "\r", ""))
			if n, err := strconv.Atoi(txt); err == nil && n > 0 && n <= 1024 {
				s.logicalCPUs = n
			}
		}
	}

	// No cmd.exe equivalent for total RAM, so this one costs a PowerShell
	// start. Acceptable: it happens once, at install.
	if ps := winBinary("powershell.exe"); ps != "" {
		out, err := runProbe(ctx, ps, "-NoProfile", "-NonInteractive", "-Command",
			"(Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory")
		if err == nil {
			txt := strings.TrimSpace(strings.ReplaceAll(string(out), "\r", ""))
			if b, err := strconv.ParseUint(txt, 10, 64); err == nil && b > 0 {
				s.memBytes = b
			}
		}
	}
	return s
}

const gib = 1024 * 1024 * 1024

// renderHostSizing produces the lines that replace @HOST_SIZING@.
//
// Policy: half the host's RAM (which is also WSL's own default, so this is not
// a grab), floored to a whole GB and clamped to [2,24] GB; swap at a quarter of
// that, matching WSL's default ratio; all logical CPUs. The point of writing
// them explicitly is not to beat the defaults; it is that the previous file
// hardcoded one machine's numbers, and anything we emit here is at least true
// of the machine it lands on.
func renderHostSizing(s hostSpecs) string {
	var b strings.Builder
	b.WriteString("# ── Generated from this Windows host at install time ──\n")

	if s.memBytes > 0 {
		memGB := (s.memBytes / 2) / gib
		if memGB < 2 {
			memGB = 2
		}
		if memGB > 24 {
			memGB = 24
		}
		swapGB := memGB / 4
		if swapGB < 1 {
			swapGB = 1
		}
		fmt.Fprintf(&b, "# host RAM: %.1f GB -> 50%%, clamped to [2,24] GB\n",
			float64(s.memBytes)/float64(gib))
		fmt.Fprintf(&b, "memory=%dGB\n", memGB)
		fmt.Fprintf(&b, "swap=%dGB\n", swapGB)
	} else {
		b.WriteString("# Host RAM could not be detected; memory/swap omitted so\n")
		b.WriteString("# WSL applies its own defaults (50% of RAM, 25% swap).\n")
	}

	if s.logicalCPUs > 0 {
		fmt.Fprintf(&b, "processors=%d\n", s.logicalCPUs)
	} else {
		b.WriteString("# Host CPU count could not be detected; processors omitted.\n")
	}

	return strings.TrimRight(b.String(), "\n")
}

// renderWslconfig substitutes the host sizing placeholder in the template.
func renderWslconfig(template string, s hostSpecs) string {
	return strings.ReplaceAll(template, "@HOST_SIZING@", renderHostSizing(s))
}

// ── /etc/wsl.conf rendering ───────────────────────────────────────────────

// currentUsername returns the account the installer is running as, or "".
//
// dfinstall refuses to run as root, so this is the real interactive user
// rather than a sudo artifact. $USER is checked first because it survives a
// container or minimal image where the passwd lookup can fail.
func currentUsername() string {
	if u := strings.TrimSpace(os.Getenv("USER")); u != "" && u != "root" {
		return u
	}
	if u, err := user.Current(); err == nil {
		name := strings.TrimSpace(u.Username)
		if name != "" && name != "root" {
			return name
		}
	}
	return ""
}

// renderWslConfContent substitutes @DEFAULT_USER@ in the /etc/wsl.conf template.
//
// An empty username omits the key entirely rather than guessing; same policy
// as the host sizing, and for the same reason: a wrong value here is worse than
// no value, since WSL falls back to the distro's initial user on its own.
func renderWslConfContent(template, username string) string {
	replacement := "# default= omitted: could not determine the installing user."
	if username != "" {
		replacement = "default=" + username
	}
	return strings.ReplaceAll(template, "@DEFAULT_USER@", replacement)
}

// renderedWslConf reads the template and renders it for this machine.
//
// ⚠ This is the SINGLE source of truth for what /etc/wsl.conf should contain.
// Install, Status and the doctor check all go through it. Comparing the raw
// template against the installed file, which is what Status and doctor used to
// do, now always mismatches, so each would report permanent, unfixable drift
// on a correctly installed machine. Exactly the failure mode the fonts module's
// doctor check had: a report that restates instead of deriving.
func renderedWslConf() ([]byte, error) {
	data, err := os.ReadFile(core.ConfigPath("wsl", "wsl.conf"))
	if err != nil {
		return nil, err
	}
	return []byte(renderWslConfContent(string(data), currentUsername())), nil
}

// wslConfState reports how /etc/wsl.conf compares to what we would install:
// "ok", "outdated", or "missing".
func wslConfState() string {
	want, err := renderedWslConf()
	if err != nil {
		return "missing"
	}
	got, err := os.ReadFile("/etc/wsl.conf")
	if err != nil {
		return "missing"
	}
	if bytes.Equal(want, got) {
		return "ok"
	}
	return "outdated"
}

// ── %USERPROFILE%\.wslconfig state ────────────────────────────────────────

// wslconfigReport is how the installed .wslconfig compares to what this repo
// declares.
type wslconfigReport struct {
	State string   // "ok", "outdated", "missing", "unknown"
	Why   string   // why the comparison could not be made, when State == "unknown"
	Drift []string // one line per key that differs, when State == "outdated"
}

// wslconfigState compares %USERPROFILE%\.wslconfig against the template.
//
// ⚠ THIS FILE IS THE ONE MOST EXPOSED TO BEING REWRITTEN FROM OUTSIDE, AND IT
// USED TO BE CHECKED BY NOTHING. installWslconfig wrote it and forgot it:
// Status() and doctor both covered /etc/wsl.conf, the sysctl drop-in, the
// Windows-home link and the shims, but never this — so a Windows-side tool
// resetting a key was silent and permanent until the next `install wsl`.
//
// ⚠ COMPARED BY KEY, NEVER BYTE-FOR-BYTE. The template holds @HOST_SIZING@ and
// is rendered per host, so a byte comparison against the raw template reports
// permanent unfixable drift, and a comparison against a fresh render would
// have to run the PowerShell/cmd.exe host probe — which Status() must not do,
// since it is a fast synchronous read with no context to cancel. Comparing the
// keys the template DECLARES sidesteps both: the sizing keys come only from
// the placeholder, so they are absent from the template's key set and are
// never compared. That is deliberate, not an oversight — memory/swap/
// processors are host-derived, and a hand-tuned `memory=` is the owner's call.
//
// Same lesson as checkWslConf and checkFonts: derive the report from the thing
// that produces the file, do not restate it.
func wslconfigState() wslconfigReport {
	tmpl, err := os.ReadFile(core.ConfigPath("wsl", "wslconfig"))
	if err != nil {
		return wslconfigReport{State: "unknown", Why: "the wslconfig template is not readable in this checkout"}
	}
	winHome := resolveWinHome()
	if winHome == "" {
		return wslconfigReport{State: "unknown", Why: "could not resolve the Windows home"}
	}
	got, err := os.ReadFile(winHome + "/.wslconfig")
	if err != nil {
		return wslconfigReport{State: "missing"}
	}
	if drift := wslconfigDrift(string(tmpl), string(got)); len(drift) > 0 {
		return wslconfigReport{State: "outdated", Drift: drift}
	}
	return wslconfigReport{State: "ok"}
}

// wslconfigDrift returns one line per key the template declares that the
// installed file does not carry with the same value. Pure, so the comparison
// is testable without a Windows host.
//
// Keys the installed file has and the template does not are NOT reported: the
// host sizing lands there legitimately, and beyond that the file is the user's
// to extend. This reports only on what this repo claims to own.
func wslconfigDrift(template, installed string) []string {
	want := parseWslconfigKeys(strings.ReplaceAll(template, "@HOST_SIZING@", ""))
	have := parseWslconfigKeys(installed)

	drift := make([]string, 0, len(want))
	for key, wantVal := range want {
		haveVal, ok := have[key]
		if !ok {
			drift = append(drift, fmt.Sprintf("%s is missing (want %s)", key, wantVal))
			continue
		}
		if !strings.EqualFold(haveVal, wantVal) {
			drift = append(drift, fmt.Sprintf("%s=%s (want %s)", key, haveVal, wantVal))
		}
	}
	sort.Strings(drift)
	return drift
}

// parseWslconfigKeys flattens an ini-shaped file to "section.key" -> value.
//
// Keys are lowercased because a rewrite from another tool may not preserve the
// camelCase this repo writes, and WSL itself does not care. Values are kept as
// written and compared case-insensitively by the caller, so `TRUE` and `true`
// do not read as drift.
func parseWslconfigKeys(data string) map[string]string {
	keys := map[string]string{}
	section := ""
	for _, line := range strings.Split(data, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.ToLower(strings.TrimSpace(line[1 : len(line)-1]))
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k = strings.ToLower(strings.TrimSpace(k))
		if k == "" {
			continue
		}
		keys[section+"."+k] = strings.TrimSpace(v)
	}
	return keys
}
