package tests

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sresarehumantoo/dotfiles/src/core"
	"github.com/sresarehumantoo/dotfiles/src/modules"
)

func TestScanCustomShellFiles_FindsCustomRC(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	// Create custom shell files
	os.WriteFile(filepath.Join(home, ".companyrc"), []byte("# work stuff"), 0644)
	os.WriteFile(filepath.Join(home, ".work_env"), []byte("export FOO=1"), 0644)
	os.WriteFile(filepath.Join(home, ".localrc"), []byte("# local"), 0644)

	discovered := modules.ScanCustomShellFiles()

	found := make(map[string]bool)
	for _, d := range discovered {
		found[d.RelPath] = true
	}

	for _, want := range []string{".companyrc", ".work_env", ".localrc"} {
		if !found[want] {
			t.Errorf("expected to find %q in scan results, got %v", want, discovered)
		}
	}
}

func TestScanCustomShellFiles_IgnoresManaged(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	// Create files that dfinstall manages — these should be excluded
	os.WriteFile(filepath.Join(home, ".zshrc"), []byte("# managed"), 0644)
	os.WriteFile(filepath.Join(home, ".bashrc"), []byte("# managed"), 0644)
	os.WriteFile(filepath.Join(home, ".aliases"), []byte("# managed"), 0644)

	discovered := modules.ScanCustomShellFiles()

	for _, d := range discovered {
		if d.RelPath == ".zshrc" || d.RelPath == ".bashrc" || d.RelPath == ".aliases" {
			t.Errorf("scan should not include managed file %q", d.RelPath)
		}
	}
}

func TestScanCustomShellFiles_IgnoresNonShell(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	// Create non-shell dotfiles that match globs
	os.WriteFile(filepath.Join(home, ".vimrc"), []byte("set nocompatible"), 0644)
	os.WriteFile(filepath.Join(home, ".npmrc"), []byte("registry=..."), 0644)
	os.WriteFile(filepath.Join(home, ".netrc"), []byte("machine ..."), 0644)

	discovered := modules.ScanCustomShellFiles()

	for _, d := range discovered {
		if d.RelPath == ".vimrc" || d.RelPath == ".npmrc" || d.RelPath == ".netrc" {
			t.Errorf("scan should not include non-shell file %q", d.RelPath)
		}
	}
}

func TestScanCustomShellFiles_IgnoresSymlinks(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	// Create a real file and a symlink
	target := filepath.Join(home, ".real_config")
	os.WriteFile(target, []byte("# real"), 0644)
	os.Symlink(target, filepath.Join(home, ".linkedrc"))
	os.WriteFile(filepath.Join(home, ".customrc"), []byte("# custom"), 0644)

	discovered := modules.ScanCustomShellFiles()

	for _, d := range discovered {
		if d.RelPath == ".linkedrc" {
			t.Error("scan should not include symlinked files")
		}
	}
}

func TestFilterNewFiles_RemovesKnown(t *testing.T) {
	core.Cfg.PreservedFiles = []string{".companyrc"}
	core.Cfg.DismissedFiles = []string{".oldrc"}
	defer func() {
		core.Cfg.PreservedFiles = nil
		core.Cfg.DismissedFiles = nil
	}()

	discovered := []modules.DiscoveredFile{
		{RelPath: ".companyrc"},
		{RelPath: ".oldrc"},
		{RelPath: ".newrc"},
	}

	filtered := modules.FilterNewFiles(discovered)

	if len(filtered) != 1 {
		t.Fatalf("expected 1 new file, got %d: %v", len(filtered), filtered)
	}
	if filtered[0].RelPath != ".newrc" {
		t.Errorf("expected .newrc, got %q", filtered[0].RelPath)
	}
}

func TestWriteCustomSourcesFile_ValidPaths(t *testing.T) {
	home := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", filepath.Join(home, ".config"))

	paths := []string{".companyrc", ".work_env"}
	err := modules.WriteCustomSourcesFile(paths)
	if err != nil {
		t.Fatalf("WriteCustomSourcesFile: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(home, ".config", "dfinstall", "custom-sources.zsh"))
	if err != nil {
		t.Fatalf("read output file: %v", err)
	}

	content := string(data)

	if !strings.Contains(content, "Generated by dfinstall") {
		t.Error("expected header comment")
	}
	if !strings.Contains(content, `[[ -f ~/.companyrc ]] && source ~/.companyrc`) {
		t.Error("expected .companyrc source line")
	}
	if !strings.Contains(content, `[[ -f ~/.work_env ]] && source ~/.work_env`) {
		t.Error("expected .work_env source line")
	}
}

func TestWriteCustomSourcesFile_RejectsInjection(t *testing.T) {
	home := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", filepath.Join(home, ".config"))

	cases := []struct {
		name string
		path string
	}{
		{"command injection", ".foo; rm -rf /"},
		{"path traversal", "../etc/passwd"},
		{"subshell", ".$(whoami)rc"},
		{"backtick", ".`id`rc"},
		{"no leading dot", "companyrc"},
		{"slash", ".config/evil"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := modules.WriteCustomSourcesFile([]string{tc.path})
			if err == nil {
				t.Errorf("expected error for path %q, got nil", tc.path)
			}
		})
	}
}

func TestMergeUnique(t *testing.T) {
	result := modules.MergeUnique([]string{"a", "b"}, []string{"b", "c", "a"})

	if len(result) != 3 {
		t.Fatalf("expected 3 items, got %d: %v", len(result), result)
	}

	expected := map[string]bool{"a": true, "b": true, "c": true}
	for _, s := range result {
		if !expected[s] {
			t.Errorf("unexpected item %q", s)
		}
	}

	// Verify order: existing items first, then new ones
	if result[0] != "a" || result[1] != "b" || result[2] != "c" {
		t.Errorf("expected [a b c], got %v", result)
	}
}
