[boot]
systemd=true
command=sysctl -p /etc/sysctl.d/99-wsl.conf

[automount]
enabled=true
root=/mnt/
options="metadata,umask=22,fmask=11"
mountFsTab=true

[network]
generateHosts=true
generateResolvConf=true

[interop]
enabled=true
appendWindowsPath=true

[user]
default=owen

[time]
useWindowsTimezone=true
